### ISSUE TITLE
InvalidGithubUrlError

### ISSUE THREAD

**Issue by labazza** [brpaz/ulauncher-cheats#3] opened 2018-12-26 13:25 UTC
When trying to add the extension i get:
 
Unexpected API error. InvalidGithubUrlError: Invalid GithubUrl: https://github.com/brpaz/ulauncher-cheats/

**Comment by brpaz** [comment] 2019-01-05 15:09
You need to add the complete url to github repo of the extension: https://github.com/brpaz/ulauncher-cheats/

**Comment by labazza** [comment] 2019-01-05 18:06
I did, i have attached screenshot

**Comment by brpaz** [comment] 2019-01-06 16:36
Strange. I tried installing the extension on my PC and it worked fine. I never seen that error before. It seems an Ulauncher error and not directly related with this extension.

There is an issue on Ulauncher repo with exactly the problem you are having: [Update or Add extension Unexpected API error. InvalidGithubUrlError: · Issue #192 · Ulauncher/Ulauncher](https://github.com/Ulauncher/Ulauncher/issues/192)

That a look there and see if it can help.

**Comment by friday** [comment] 2019-01-06 18:33
It's because of the trailing slash. Will hopefully be fixed eventually, but in the meanwhile remove the slash.

**Comment by labazza** [comment] 2019-01-06 18:38
removing the trailing slash i get a different error:

 Unexpected API error. BadZipfile: File is not a zip file

The steps of  Issue #192 executed in python2 are successful:
>>> branch_head_url = 'https://api.github.com/repos/brpaz/ulauncher-cheats/git/refs/heads/master'
>>> branch_head = json.load(urlopen(branch_head_url))
>>> branch_head_commit = json.load(urlopen(branch_head['object']['url']))
>>>

**Comment by friday** [comment] 2019-01-06 18:45
It may still be a Ulauncher issue rather than a ulauncher-cheats issue. Please exit ulauncher and run it from the terminal with `ulauncher -v` to get verbose info. Try to locate the line of code it crashed on and paste here to @brpaz and he may be able to help you further (I don't even use this extension, came here since I noticed it was linked from the slash issue)

**Comment by labazza** [comment] 2019-01-06 18:52
```
2019-01-06 19:51:25,463 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. BadZipfile: File is not a zip file
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 355, in prefs_extension_add
    ext_id = downloader.download(url)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 63, in download
    unzip(filename, ext_path)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 171, in unzip
    with ZipFile(filename) as zipfile:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file


```

**Comment by friday** [comment] 2019-01-07 15:12
Definitely not a ulauncher-cheats issue. It isn't even installed when it's happening.

Might not *directly* be a Ulauncher issue (could be because of your python libs, network, or cached files), but creating an issue there instead isn't wrong.

You could try removing ulauncher's download cache `rm -rf /tmp/ulauncher_dl_*` and try again, in case it's a side-effect of the earlier issue. 
Otherwise create an issue here: https://github.com/Ulauncher/Ulauncher/issues

**Comment by brpaz** [comment] 2019-01-13 12:30
I will close this issue as I cannot reproduce this in my machine and seems unlikely but be an issue with the extension itself.

**Closed by brpaz** 2019-01-13 12:30 UTC
